name: Build docs

on:
  push:
    branches: [ main ]

jobs:
  fmt:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cargo doc
          echo "<meta http-equiv=\"refresh\" content=\"0; url=build_wheel\">" > target/doc/index.html
          cp -r target/doc ./tmpdocs
          git config user.email "you@example.com"
          git config user.name "CI"
          git checkout -b gh-pages
          rm -rf ./docs
          mv tmpdocs docs
          git add docs
          git commit -m "Update docs"
          git push --set-upstream origin gh-pages
