name: Build docs

on:
  push:
    branches: [ main ]

jobs:
  fmt:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          cargo doc
          export FIRST_PACKAGE=`cargo metadata --no-deps --format-version=1 | jq -r '.packages[] | .name'`
          echo "<meta http-equiv=\"refresh\" content=\"0; url=$FIRST_PACKAGE/index.html\">" > target/doc/index.html
          cp -r target/doc ./tmpdocs
          git config user.email "you@example.com"
          git config user.name "CI"
          git checkout gh-pages
          rm -rf ./docs
          mv tmpdocs docs
          git add docs
          git commit -m "Update docs"
          git push
